name: Deploy Docusaurus to GitHub Pages Repo

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. 拉取仓库代码
      # https://github.com/actions/checkout/releases
      - name: Checkout Source Code
        uses: actions/checkout@v7

      # 2. 安装 pnpm
      # https://github.com/pnpm/action-setup/releases
      - name: Install pnpm
        uses: pnpm/action-setup@v6
        with:
          # 不指定 pnpm 版本, 默认使用 package.json 中配置的 packageManager 版本
          # version: 11.4.0
          cache: true

      # 3. 设置 Node.js 环境
      # https://github.com/actions/setup-node/releases
      - name: Set up Node.js
        uses: actions/setup-node@v7
        with:
          node-version: "24.11.1" # 或者指定具其他版本

      # 4. 安装依赖
      - name: Install Dependencies
        run: pnpm install --frozen-lockfile # 使用 frozen-lockfile 确保依赖版本与 pnpm-lock.yaml 完全一致

      # 5. 构建 Docusaurus 静态文件
      - name: Build Website
        run: pnpm run build

      # 6. 将构建产物部署到目标仓库
      # https://github.com/JamesIves/github-pages-deploy-action/releases
      - name: Deploy to Target Repo
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.DEPLOY_TOKEN_TEMP }}
          repository-name: ituknown/ituknown.github.io
          branch: main # 目标仓库接收静态文件的分支
          folder: build # Docusaurus 默认构建输出的目录
          clean: true # 部署时自动清理目标分支中旧的多余文件
