name: Push to GitLab

on:
  push:
    branches: ["main"]

jobs:
  push-to-gitlab:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7
        with:
          fetch-depth: 0 # 完整的 git 历史

      - name: Push to GitLab Remote
        env:
          GITLAB_TOKEN: ${{ secrets.GITLAB_PAT }} # GitLab Token
        run: |
          # 配置远程 GitLab 地址，并带上 Token 认证
          git remote add gitlab https://oauth2:${{ env.GITLAB_TOKEN }}@gitlab.com/${{ github.REPOSITORY }}.git

          # 将 main 分支 push 到 gitlab
          git push gitlab main
